app.js
package-lock.json
package.json
routes/stock.js

- [ ✅ ]  이 프로젝트의 코드 스타일을 따르나요?
- [ ✅ ]  develop 브랜치로 pull request 했나요?
<br>
- [✅ ] api 호출 위한 토큰 변경

feat: 발행한 접근 토큰 적용

---

database/connect/mariadb.js
routes/stock.js

- [✅ ]  이 프로젝트의 코드 스타일을 따르나요?
<br>
- [✅] 토큰 변경

fix : 재무제표 페이지 토큰 변경

---

app.js
routes/finstat.js
routes/stock.js

feat: 일별시세API 구현

---

app.js
database/connect/mariadb.js
routes/keyword.js

feat: wordcloud with keyword

---

routes/finstat.js
routes/stock.js

feat: 일별시세 API 수정

---

routes/stock.js

feat: 토큰 발행 자동화 구현

---

app.js
database/connect/mariadb.js
package-lock.json
package.json
utils/BatchStocks.js
utils/StockList.js

전체 종목 데이터 가져오고 DB 업데이트 (배치 작업)

---

app.js
database/connect/mariadb.js
database/news/detail.js
database/news/list.js
database/news/tag.js
routes/main.js
routes/news.js
utils/time.js

feat : add news and newsDetail api

---

bin/www
package-lock.json
package.json
socket.js

- [O]  이 프로젝트의 코드 스타일을 따르나요?
- [O]  develop 브랜치로 pull request 했나요?
<br>
- Task 1 : 서버 웹소켓 연결
- Task 2 : 서버 실행 시 웹소켓 키 자동 발급

feat: 서버 웹소켓 연결

---

app.js
routes/chart.js
utils/BatchStocks.js
utils/token/EbestToken.js

각 종목에 대한 당일 Chart 구현 (9:00 ~ 현재시각)

---

socket.js

- [O]  이 프로젝트의 코드 스타일을 따르나요?
- [O]  develop 브랜치로 pull request 했나요?
<br>

fix: 백엔드 한투 API KEY .env파일 수정

---

socket.js

- [O]  이 프로젝트의 코드 스타일을 따르나요?
- [O]  develop 브랜치로 pull request 했나요?
<br>

fix: socket파일 수정

---

database/news/tag.js
routes/news.js

feat: add keyword block setting in news detail page

---

database/connect/mariadb.js
routes/search.js

feat: search page

---

app.js
routes/stockInfo.js
socket.js
utils/StockInfo.js
utils/token/KOInvToken.js

- [O]  이 프로젝트의 코드 스타일을 따르나요?
- [O]  develop 브랜치로 pull request 했나요?
<br>
- [O] Task 1 : 메인페이지 상단 종목정보 라우팅 완료(웹소켓 제외)

feat: 메인페이지 상단 부분 종목정보

---

routes/chart.js

Chart api 기준 날짜 설정

---

database/connect/mariadb.js
routes/finstat.js
routes/stock.js

<br>
- [✅] 재무제표 DB에 저장
- [✅] 조회 api 구현

feat: 재무제표 정보 DB에 저장 및 조회 api 구현

---

database/connect/mariadb.js
routes/finstat.js
routes/stock.js

fix: 오류 수정

---

app.js
routes/main.js
routes/news.js
routes/stockInfo.js
utils/StockInfo.js

- []  이 프로젝트의 코드 스타일을 따르나요?
<br>

fix: 한투 토큰 갱신

---

database/connect/mariadb.js

docs: search페이지 select문 수정

---

database/connect/mariadb.js

docs: desc 삭제

---

routes/main.js
utils/TopKeyword.js

<br>
- [✅] 상위 키워드 추출 API 구현
- [✅] 키워드에 대한 종목 정보 추출

feat: 상위 키워드 API 구현

---

app.js
routes/flask.js
socket.js

feat: add news detail sentiment analysis api

---

app.js
routes/finstat.js
routes/mypage.js
routes/stock.js
routes/stockInfo.js

feat: 로그인 구현 및 토큰 갱신

---

routes/stock.js
routes/stockInfo.js
socket.js

feat: add real-time data time in socket

---

database/news/list.js
routes/news.js

refactor: modify related parts according to updated news table

---

database/connect/mariadb.js
routes/stock.js
routes/stockInfo.js

fix: select order by 삭제

---

routes/stock.js
routes/stockInfo.js
utils/TopKeyword.js

키워드디테일 추가 정보 가져오기

---

app.js
routes/chart.js
routes/stockInfo.js

차트 예외처리 및 현재 시각 이후 가격 null 처리, socket 데이터 추가

---

socket.js

socket으로 가져오는 실시간 데이터 추가

---

routes/main.js
routes/mypage.js
routes/stock.js
routes/stockInfo.js
routes/users.js
utils/MyStock.js
utils/Signup.js

feat: 메인페이지 마이stock 관련 기능 추가

---

routes/stock.js
utils/MyStock.js

fix: stock.js에서 access토큰 잘못 가져오던 것 수정

---

app.js
database/connect/mariadb.js
database/news/list.js
routes/finstat.js
routes/keyword.js
routes/main.js
routes/news.js
routes/search.js
routes/stockInfo.js
socket.js
utils/MyStock.js

fix: console.log 간소화 및 한투토큰 자동화

---

database/connect/mariadb.js
routes/flask.js
routes/stockInfo.js
routes/users.js

chore: db 주소 변경

---

database/connect/mariadb.js
routes/search.js

feat: 검색페이지에서 무한스크롤 적용

---

routes/stockInfo.js

fix: 접근토큰 문제 해결
